"""Registers `seam_fixtures` (the trusted seam to cerberus internals) with pytest."""

from seam_fixtures import (
    check_result,
    ctx,
    error,
    fail,
    fake_proc,
    fake_registry,
    git_history_unavailable_error,
    graph_search,
    known_check_ids,
    local_source,
    make_context,
    no_git,
    ok,
    register_fake_check,
    repo,
    rumdl_canonical,
    run_check,
    run_check_on_disk,
    run_check_with_files,
    run_check_with_workflows,
    scope,
    skip,
    status,
)

__all__ = [
    "check_result",
    "ctx",
    "error",
    "fail",
    "fake_proc",
    "fake_registry",
    "git_history_unavailable_error",
    "graph_search",
    "known_check_ids",
    "local_source",
    "make_context",
    "no_git",
    "ok",
    "register_fake_check",
    "repo",
    "rumdl_canonical",
    "run_check",
    "run_check_on_disk",
    "run_check_with_files",
    "run_check_with_workflows",
    "scope",
    "skip",
    "status",
]
